version: "3.4"

services:
  gateway:
    image: $PHRASEANET_DOCKER_REGISTRY/phraseanet-nginx:$PHRASEANET_DOCKER_TAG
    restart: on-failure
    volumes:
        - data_vol:/var/data
        - ./www/custom:/var/alchemy/www/custom
        # Uncomment this if you want to use an alternate nginx config
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - phraseanet
    ports:
      - ${PHRASEANET_APP_PORT}:80

  phraseanet:
    image: $PHRASEANET_DOCKER_REGISTRY/phraseanet:$PHRASEANET_DOCKER_TAG
    restart: on-failure
    depends_on:
      - db
      - redis
      - rabbitmq
      - elasticsearch
    volumes:
      - data_vol:/var/data
      - ./config/:/var/alchemy/config:rw
      - tmp_vol:/var/alchemy/tmp:rw
      - tmp_locks_vol:/var/alchemy/tmp/locks:rw
      - tmp_caption_vol:/var/alchemy/tmp/caption:rw
      - tmp_lazaret_vol:/var/alchemy/tmp/lazaret:rw
      - tmp_download_vol:/var/alchemy/tmp/download:rw
      # @TODO : waiting for a resolution
      - resources_proxy:/var/alchemy/resources/proxies:rw

  worker:
    image: $PHRASEANET_DOCKER_REGISTRY/phraseanet:$PHRASEANET_DOCKER_TAG
    restart: on-failure
    depends_on:
      - db
      - redis
      - rabbitmq
      - elasticsearch
    entrypoint: []
    command:
    - "/usr/bin/supervisord"
    - "-n"
    - "-c"
    - "/etc/supervisor/supervisord.conf"
    volumes:
      - data_vol:/var/data

  db:
    image: $PHRASEANET_DOCKER_REGISTRY/phraseanet-db:$PHRASEANET_DOCKER_TAG
    restart: on-failure
    environment:
      - MYSQL_ROOT_PASSWORD
    volumes:
     - db_vol:/var/lib/mysql

  rabbitmq:
    image: rabbitmq:3-management
    restart: on-failure
    environment:
      - RABBITMQ_DEFAULT_USER
      - RABBITMQ_DEFAULT_PASS

  redis:
    image: redis
    restart: on-failure

  elasticsearch:
    image: $PHRASEANET_DOCKER_REGISTRY/phraseanet-elasticsearch:$PHRASEANET_DOCKER_TAG
    build: ./elasticsearch
    restart: on-failure
    volumes:
      - elasticsearch_vol:/usr/share/elasticsearch/data

volumes:
  data_vol:
    driver: local
  tmp_vol:
    driver: local
  tmp_locks_vol:
    driver: local
  tmp_caption_vol:
    driver: local
  tmp_lazaret_vol:
    driver: local
  tmp_download_vol:
    driver: local
  db_vol:
    driver: local
  elasticsearch_vol:
    driver: local
  dev_vol:
    driver: local
  # @TODO : waiting for a resolution
  resources_proxy:
    driver: local

