version: "3.4"
services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    networks:
      - internal
    ports:
      - 8080:80
    depends_on:
      - db

  dev:
    build:
      context: dev
    networks:
      - internal
    stdin_open: true
    tty: true
    hostname: local
    environment:
      - SYMFONY_ENV
      - SSH_AUTH_SOCK=/ssh-auth-sock
    depends_on:
      - db
      - redis
      - rabbitmq
      - elasticsearch
      - phraseanet
    volumes:
      - app_vol:/var/Phraseanet
      - data_vol:/var/data
      - dev_vol:/home/app
      - ~/.ssh:/home/app/.ssh
